### PR TITLE
New contract filters added

### PR DESCRIPTION
**Pull request by mabuturabcloudelligent**
Issue 1407
Document type, contract type and language filter added

### CODE REVIEW

**Comment by charlesyoung** [comment]
@mabuturabcloudelligent I agreed with Zahra that we wouldn't add the company filter but CCSI has asked that this could be added. I agreed to leave it out because the RC companies data isn't that clean with many duplicate entries. The OLC company data however seems much better which is why Sam has requested that we include a company filter. Will this be possible? 

cc @zaid-azmat

**Comment by mabuturab1** [comment]
> @mabuturabcloudelligent I agreed with Zahra that we wouldn't add the company filter but CCSI has asked that this could be added. I agreed to leave it out because the RC companies data isn't that clean with many duplicate entries. The OLC company data however seems much better which is why Sam has requested that we include a company filter. Will this be possible?
> 
> cc @zaid-azmat

Are you looking for a dropdown, or a search text for the company because on backend we have a search text

And I believe you are already aware about the possible issue that can come due to the company name entered or selected being different one then whats in the contract and it can lead to a bit of uncertainty whether search is working correctly or not
You are quite aware about possible implications I believe

**Comment by SamCCSI** [comment]
Drop down.

Apart from dirty data, what are the implications?

**Comment by mabuturab1** [comment]
> Drop down. Apart from dirty data, what are the implications?

@SamCCSI Its mainly that you may not achieve desired filtering behaviour in some cases where data is dirty
But as you already know that so lets just proceed for now
I will look on further into dropdown requirement and will get back if I have any query

**Comment by SamCCSI** [comment]
hi @mabuturab1 is this ready for us to review? I'm not seeing anything on the back-end

**Comment by mabuturabcloudelligent** [comment]
> hi @mabuturab1 is this ready for us to review? I'm not seeing anything on the back-end

No, not now
We will inform once code is tested and deployed
This pull request was for internal testing purpose and does not include company name filters. We will get back once everything is ready for review,

**Comment by charlesyoung** [comment]
@mabuturab1 can you please sort the company name in the dropdown menu alphabetically? Thanks

**Pull request merged**
